version: '3.8'

services:
  # Backend (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto-arb-backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    networks:
      - crypto-arb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://0.0.0.0:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crypto-arb-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REACT_APP_WS_URL=ws://localhost:8080/ws
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - crypto-arb-network
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  crypto-arb-network:
    driver: bridge 